services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./wg_confs:/config/wg_confs/
    ports:
      - 54972:54972/udp
      - 8080:80/tcp # Allow access to speedtest-tracker
    env_file: "wireguard.env"
    healthcheck:
      test: ["CMD-SHELL", "curl -f --connect-timeout 5 $$HEALTHCHECK_URL"]
      start_period: 15s
      start_interval: 5s
      interval: 1m
      timeout: 10s
      retries: 5
    restart: always
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    env_file: "speedtest-tracker.env"
    volumes:
      - ./speedtest-tracker-data:/config
    network_mode: "service:wireguard" # Use Wireguard container's interfaces
    depends_on:
      wireguard:
        condition: service_healthy
    restart: unless-stopped
volumes:
    speedtest-tracker:
